require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - resource
    - route_param
